# traefik/dynamic/routers.yml

http:
  routers:
    authentik:
      rule: "Host(`authentik.joetaylor.me`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: authentik-service

    netdata:
      rule: "Host(`netdata.joetaylor.me`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: netdata-service
      middlewares:
        - authentik-forward-auth@file

    pihole:
      rule: "Host(`pihole.joetaylor.me`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: pihole-service
      middlewares:
        - authentik-forward-auth@file

    portainer:
      rule: "Host(`portainer.joetaylor.me`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: portainer-service
      middlewares:
        - authentik-forward-auth@file

    # uptime-kuma:
    #   rule: "Host(`uptime.joetaylor.me`)"
    #   entryPoints:
    #     - websecure
    #   tls:
    #     certResolver: cloudflare
    #   service: uptime-kuma-service
    #   middlewares:
    #     - authentik-forward-auth@file

    dozzle:
      rule: "Host(`dozzle.joetaylor.me`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: dozzle-service
      middlewares:
        - authentik-forward-auth@file

    traefik-dashboard:
      rule: "Host(`traefik.joetaylor.me`)"
      service: api@internal
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      middlewares:
        - authentik-forward-auth@file

    http-catchall:
      rule: "HostRegexp(`{host:.+}`)"
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: noop-service

    catchall-router:
      rule: "HostRegexp(`{host:.+}`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      middlewares:
        - authentik-forward-auth@file
      service: noop-service

    n8n:
      rule: "Host(`n8n.joetaylor.me`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: n8n-service
      # middlewares:
      #   - authentik-forward-auth@file

    # fider:
    #   rule: "Host(`fider.joetaylor.me`)"
    #   entryPoints:
    #     - websecure
    #   tls:
    #     certResolver: cloudflare
    #   service: fider-service
      # Uncomment if authentication is needed
      # middlewares:
      #   - authentik-forward-auth@file

    dashy:
      rule: "Host(`home.joetaylor.me`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: dashy-service
      middlewares:
        - authentik-forward-auth@file

    nocodb:
      rule: "Host(`nocodb.joetaylor.me`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: nocodb-service
      middlewares:
        - authentik-forward-auth@file

    # mattermost:
    #   rule: "Host(`mattermost.joetaylor.me`)"
    #   entryPoints:
    #     - websecure
    #   tls:
    #     certResolver: cloudflare
    #   service: mattermost-service
    #   middlewares:
    #     - authentik-forward-auth@file

    # affine:
    #   rule: "Host(`affine.joetaylor.me`)"
    #   entryPoints:
    #     - websecure
    #   tls:
    #     certResolver: cloudflare
    #   service: affine-service
    #   middlewares:
    #     - authentik-forward-auth@file

    ghost:
      rule: "Host(`blog.joetaylor.me`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: ghost-service
      # middlewares:
      #   - authentik-forward-auth@file  # Remove or comment out if you don't want authentication for Ghost - blog/newsletter

    supabase-studio:
      rule: "Host(`supabase.joetaylor.me`)"
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
      service: supabase-studio-service
      middlewares:
        - authentik-forward-auth@file